import { all, takeLatest } from "redux-saga/effects";
import {
  handleOnCourseLoading,
  handleOnMyCourseLoading,
  handleOnGetEnrollId,
  handleOnGetLearning,
  handleOnSaveTrackingLesson,
  handleOnGetTrackingLesson,
  handleOnSaveTrackingVideo,
  handleOnUpdateCompletedVideo,
  handleLoadProgress,
  handleOnFreeCourseLoading,
  handleOnBestSellerCourseLoading,
  handleOnRelatedCourseLoading,
  handleOnManualSelectedLesson,
  handleLoadNote,
  handleSaveNote,
  handleDeleteNote,
  handleSavePost,
  handleSaveReplyToPost,
  handleSaveLikeOfPost,
  handleLoadNotification,
  handleReadNotification,
  handleDeletePost,
  handleRemoveReplyInPost,
  handleUpdateUserRating,
  handleLoadCourseRating,
  handleReadAllNotification,
  handleGenerateCourseExam,
  handleFinishExam,
  handleRetakeExam,
  handleLoadAccomplishmentsExam,
  handleLoadCertificate,
  handleDownloadCertificate,
  handleOnGetMyLearning,
  handleAllNotification,
  handleDeleteNotification,
  handleAllDeleteNotification,
} from "./courseHandlers";
import {
  onBestSellerCourseLoading,
  onCourseLoading,
  onDeleteNote,
  onDeletePost,
  onDownloadCertificate,
  onFinishExam,
  onFreeCourseLoading,
  onGenerateCourseExam,
  onGetEnrollId,
  onGetLearning,
  onGetMyLearning,
  onGetTrackingLesson,
  onLoadAccomplishmentsExam,
  onLoadCertificate,
  onLoadCourseRating,
  onLoadNote,
  onLoadNotification,
  onLoadProgress,
  onManualSelectedLesson,
  onMyCourseLoading,
  onReadAllNotification,
  onReadNotification,
  onRelatedCourseLoading,
  onRemoveReplyInPost,
  onRetakeExam,
  onSaveLikeOfPost,
  onSaveNote,
  onSavePost,
  onSaveReplyToPost,
  onSaveTrackingLesson,
  onSaveTrackingVideo,
  onUpdateCompletedVideo,
  onUpdateUserRating,
  onAllNotification,
  onDeleteNotification,
  onAllDeleteNotification,
} from "./courseSlice";

/**
 * after declare a Saga, assign into rootSaga
 */
export default function* courseSaga() {
  yield all([
    takeLatest(onMyCourseLoading.type, handleOnMyCourseLoading),
    takeLatest(onCourseLoading.type, handleOnCourseLoading),
    takeLatest(onFreeCourseLoading.type, handleOnFreeCourseLoading),
    takeLatest(onBestSellerCourseLoading.type, handleOnBestSellerCourseLoading),
    takeLatest(onRelatedCourseLoading.type, handleOnRelatedCourseLoading),
    takeLatest(onGetEnrollId.type, handleOnGetEnrollId),
    takeLatest(onGetLearning.type, handleOnGetLearning),
    takeLatest(onGetMyLearning.type, handleOnGetMyLearning),
    takeLatest(onManualSelectedLesson.type, handleOnManualSelectedLesson),
    takeLatest(onGetTrackingLesson.type, handleOnGetTrackingLesson),
    takeLatest(onSaveTrackingLesson.type, handleOnSaveTrackingLesson),
    takeLatest(onSaveTrackingVideo.type, handleOnSaveTrackingVideo),
    takeLatest(onUpdateCompletedVideo.type, handleOnUpdateCompletedVideo),
    takeLatest(onLoadProgress.type, handleLoadProgress),
    takeLatest(onLoadNote.type, handleLoadNote),
    takeLatest(onSaveNote.type, handleSaveNote),
    takeLatest(onDeleteNote.type, handleDeleteNote),
    takeLatest(onSavePost.type, handleSavePost),
    takeLatest(onDeletePost.type, handleDeletePost),
    takeLatest(onSaveReplyToPost.type, handleSaveReplyToPost),
    takeLatest(onRemoveReplyInPost.type, handleRemoveReplyInPost),
    takeLatest(onSaveLikeOfPost.type, handleSaveLikeOfPost),
    takeLatest(onLoadNotification.type, handleLoadNotification),
    takeLatest(onReadNotification.type, handleReadNotification),
    takeLatest(onReadAllNotification.type, handleReadAllNotification),
    takeLatest(onUpdateUserRating.type, handleUpdateUserRating),
    takeLatest(onLoadCourseRating.type, handleLoadCourseRating),
    takeLatest(onGenerateCourseExam.type, handleGenerateCourseExam),
    takeLatest(onFinishExam.type, handleFinishExam),
    takeLatest(onRetakeExam.type, handleRetakeExam),
    takeLatest(onLoadAccomplishmentsExam.type, handleLoadAccomplishmentsExam),
    takeLatest(onLoadCertificate.type, handleLoadCertificate),
    takeLatest(onDownloadCertificate.type, handleDownloadCertificate),
    takeLatest(onAllNotification.type, handleAllNotification),
    takeLatest(onDeleteNotification.type,handleDeleteNotification),
    takeLatest(onAllDeleteNotification.type,handleAllDeleteNotification),
  ]);
}
